apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: frames-fanout
spec:
  name: frames-fanout
  vhost: "/service_0" # default to '/' if not provided
  type: fanout # default to 'direct' if not provided
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: production # rabbitmqCluster must exist in the same namespace as this resource
