apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rw-permission
spec:
  vhost: "/"
  user: "username"
  permissions:
    write: ".*"
    configure: ""
    read: ".*"
  rabbitmqClusterReference:
    name: production
