# {
# "name":"reception-status-frame-delivered-to-globus-exchange",
# "vhost":"/",
# "type":"fanout",
# "durable":true,
# "auto_delete":false,
# "internal":false,
# "arguments":{}
# }
    
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: reception-status-frame-delivered-to-globus-exchange
spec:
  name: reception-status-frame-delivered-to-globus-exchange # name of the exchange
  vhost: "/"
  type: fanout # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  # internal: false    ### TODO - not working
  rabbitmqClusterReference:
    name: rb-cluster-1    
