apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: guest-permission
spec:
  vhost: "/"
  user: "guest" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rb-cluster-1