# {
# "name":"reception-status-frame-delivered-to-globus_5-dlx",
# "vhost":"/",
# "durable":true,
# "auto_delete":false,
# "arguments":{"x-dead-letter-exchange":"reception-status-frame-delivered-to-globus-exchange","x-message-ttl":5000}
# }


apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: qq-5-dlx
spec:
  name: qq-5-dlx
  pattern: "^qq-reception-status-frame-delivered-to-globus_5-dlx$" 
  applyTo: "queues" # set to 'queues', 'exchanges', or 'all'
  definition:
    dead-letter-strategy: at-least-once
    overflow: reject-publish  
    ## It is recommended to additionally configure max-length or max-length-bytes to prevent excessive message buildup in the source quorum queue
    # max-length: 1000
    dead-letter-exchange: reception-status-frame-delivered-to-globus-exchange
    message-ttl: 5000



  rabbitmqClusterReference:
    name: rb-cluster-1

---

#  {
#   "name":"reception-status-frame-delivered-to-globus",
#   "vhost":"/",
#   "durable":true,
#   "auto_delete":false,
#   "arguments":{"x-dead-letter-exchange":"reception-status-frame-delivered-to-globus_5-dlx-exchange"}
# }

apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: qq-globus
spec:
  name: qq-globus
  pattern: "^qq-reception-status-frame-delivered-to-globus$" 
  applyTo: "queues" # set to 'queues', 'exchanges', or 'all'
  definition:
    dead-letter-strategy: at-least-once
    overflow: reject-publish  
    ## It is recommended to additionally configure max-length or max-length-bytes to prevent excessive message buildup in the source quorum queue
    # max-length: 1000  
    dead-letter-exchange: reception-status-frame-delivered-to-globus_5-dlx-exchange
  rabbitmqClusterReference:
    name: rb-cluster-1
