# {
# "name":"reception-status-frame-delivered-to-globus_5-dlx",
# "vhost":"/",
# "durable":true,
# "auto_delete":false,
# "arguments":{"x-dead-letter-exchange":"reception-status-frame-delivered-to-globus-exchange","x-message-ttl":5000}
# }
        
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: qq-reception-status-frame-delivered-to-globus-5-dlx
spec:
  name: qq-reception-status-frame-delivered-to-globus_5-dlx
  vhost: "/"
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rb-cluster-1 


---

#  {
#   "name":"reception-status-frame-delivered-to-globus",
#   "vhost":"/",
#   "durable":true,
#   "auto_delete":false,
#   "arguments":{"x-dead-letter-exchange":"reception-status-frame-delivered-to-globus_5-dlx-exchange"}
# }


apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: qq-reception-status-frame-delivered-to-globus
  
spec:
  name: qq-reception-status-frame-delivered-to-globus
  vhost: "/"
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rb-cluster-1 