apiVersion: v1
kind: Secret
metadata:
  name: rabbit-user-guest
  namespace: rabbitmq-demo2
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
type: Opaque
---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: guest
  namespace: rabbitmq-demo2
spec:
  tags:
  - policymaker
#  - monitoring 
#  - management
  - administrator
  rabbitmqClusterReference:
    name: rb-cluster-1
  importCredentialsSecret:
    name: rabbit-user-guest # name of the secret